### ISSUE TITLE
Kindly asking contribution rules and License

### ISSUE THREAD

**Issue by twbabyduck** [superliuxz/DBSCAN#22]
Hi William,

I made some changes in code in order to achieve better performance on cpu and not yet commit to the repository because you might have specific contribution rules. One more thing is that if it is okay to put MIT License for later development in a fork repository.

Thanks

**Comment by superliuxz** [comment]
Hi,

Please make a fork (i see you already did), and feel free to contribute to your fork. I've added GPL license to the project.

I am pretty sure there is tons of room for improvement. Enjoy.

**Comment by twbabyduck** [comment]
Okie! I was hoping it will be MIT or BSD License so that company could benefit from it. What do you think?
